### ISSUE TITLE
Provide ES5 Example

### ISSUE THREAD

**Issue by BobbyKostadinov** [dowjones/namespaced-console-logger#1]
Is it possible to provide ES5 require example for node and browser ? 
ES6 import might confuse developers and lead to code not working on old browsers

**Comment by nemtsov** [comment]
@BobbyKostadinov since ES2015 is a standard, I feel like we should be moving forward as a community and use the latest version of the language. That being said, here's the same example from the README in ES5: 

``` js
var createLoggers = require('namespaced-console-logger');

var loggers = createLoggers();
var logger = loggers.get('namespace');

logger.info('Hello %s!', 'world');
```
